//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ZivotinjeModel", "fk_zoo", "zoo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ZivotinjeModel.zoo), "zivotinja", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ZivotinjeModel.zivotinja), true)]

#endregion

namespace ZivotinjeModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DatabaseEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DatabaseEntities object using the connection string found in the 'DatabaseEntities' section of the application configuration file.
        /// </summary>
        public DatabaseEntities() : base("name=DatabaseEntities", "DatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DatabaseEntities object.
        /// </summary>
        public DatabaseEntities(string connectionString) : base(connectionString, "DatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DatabaseEntities object.
        /// </summary>
        public DatabaseEntities(EntityConnection connection) : base(connection, "DatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<zivotinja> zivotinja
        {
            get
            {
                if ((_zivotinja == null))
                {
                    _zivotinja = base.CreateObjectSet<zivotinja>("zivotinja");
                }
                return _zivotinja;
            }
        }
        private ObjectSet<zivotinja> _zivotinja;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<zoo> zoo
        {
            get
            {
                if ((_zoo == null))
                {
                    _zoo = base.CreateObjectSet<zoo>("zoo");
                }
                return _zoo;
            }
        }
        private ObjectSet<zoo> _zoo;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the zivotinja EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTozivotinja(zivotinja zivotinja)
        {
            base.AddObject("zivotinja", zivotinja);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the zoo EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTozoo(zoo zoo)
        {
            base.AddObject("zoo", zoo);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ZivotinjeModel", Name="zivotinja")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class zivotinja : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new zivotinja object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="ime">Initial value of the ime property.</param>
        /// <param name="vrsta">Initial value of the vrsta property.</param>
        /// <param name="zooId">Initial value of the zooId property.</param>
        public static zivotinja Createzivotinja(global::System.Int32 id, global::System.String ime, global::System.String vrsta, global::System.Int32 zooId)
        {
            zivotinja zivotinja = new zivotinja();
            zivotinja.id = id;
            zivotinja.ime = ime;
            zivotinja.vrsta = vrsta;
            zivotinja.zooId = zooId;
            return zivotinja;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ime
        {
            get
            {
                return _ime;
            }
            set
            {
                OnimeChanging(value);
                ReportPropertyChanging("ime");
                _ime = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ime");
                OnimeChanged();
            }
        }
        private global::System.String _ime;
        partial void OnimeChanging(global::System.String value);
        partial void OnimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String vrsta
        {
            get
            {
                return _vrsta;
            }
            set
            {
                OnvrstaChanging(value);
                ReportPropertyChanging("vrsta");
                _vrsta = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("vrsta");
                OnvrstaChanged();
            }
        }
        private global::System.String _vrsta;
        partial void OnvrstaChanging(global::System.String value);
        partial void OnvrstaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 zooId
        {
            get
            {
                return _zooId;
            }
            set
            {
                OnzooIdChanging(value);
                ReportPropertyChanging("zooId");
                _zooId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("zooId");
                OnzooIdChanged();
            }
        }
        private global::System.Int32 _zooId;
        partial void OnzooIdChanging(global::System.Int32 value);
        partial void OnzooIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ZivotinjeModel", "fk_zoo", "zoo")]
        public zoo zoo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<zoo>("ZivotinjeModel.fk_zoo", "zoo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<zoo>("ZivotinjeModel.fk_zoo", "zoo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<zoo> zooReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<zoo>("ZivotinjeModel.fk_zoo", "zoo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<zoo>("ZivotinjeModel.fk_zoo", "zoo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ZivotinjeModel", Name="zoo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class zoo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new zoo object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="grad">Initial value of the grad property.</param>
        public static zoo Createzoo(global::System.Int32 id, global::System.String grad)
        {
            zoo zoo = new zoo();
            zoo.id = id;
            zoo.grad = grad;
            return zoo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String grad
        {
            get
            {
                return _grad;
            }
            set
            {
                OngradChanging(value);
                ReportPropertyChanging("grad");
                _grad = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("grad");
                OngradChanged();
            }
        }
        private global::System.String _grad;
        partial void OngradChanging(global::System.String value);
        partial void OngradChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ZivotinjeModel", "fk_zoo", "zivotinja")]
        public EntityCollection<zivotinja> zivotinja
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<zivotinja>("ZivotinjeModel.fk_zoo", "zivotinja");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<zivotinja>("ZivotinjeModel.fk_zoo", "zivotinja", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
