//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class drzave
{
    public drzave()
    {
        this.gradovi = new HashSet<gradovi>();
    }

    public int id { get; set; }
    public string naziv { get; set; }

    public virtual ICollection<gradovi> gradovi { get; set; }
}

public partial class gradovi
{
    public int id { get; set; }
    public string naziv { get; set; }
    public Nullable<int> drzavaId { get; set; }

    public virtual drzave drzave { get; set; }
}
