//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Pas
{
    public int id { get; set; }
    public string ime { get; set; }
    public Nullable<int> vlasnikId { get; set; }

    public virtual Vlasnik Vlasnik { get; set; }
}

public partial class Vlasnik
{
    public Vlasnik()
    {
        this.Pas = new HashSet<Pas>();
    }

    public int id { get; set; }
    public string ime { get; set; }

    public virtual ICollection<Pas> Pas { get; set; }
}
